general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(262626ff)
    blur_passes = 0
}

input-field {
    monitor =
    size = 500, 70
    position = 0, 0
    halign = center
    valign = center
    inner_color = rgba(404040ff)
    outer_color = rgba(ffcc66ff)
    font_color = rgba(e6e6e6ff)
    check_color = rgba(66cc66ff)
    fail_color = rgba(e65c5cff)
    outline_thickness = 3
    placeholder_text = Enter Password
    rounding = 0
    fade_on_empty = false
}
